### ISSUE TITLE
Manually activate the tab In Dialog

### ISSUE THREAD

**Issue by DrastiGohel** [serenity-is/common-features#10]
Hi,

I am trying to open a tab from Dialog at the click of the button in the grid.
Trying the code below which failed to work.
this.element.closest('.ui-tabs').tabs('option', ''active", 0)

Please suggest. 

![image](https://user-images.githubusercontent.com/98172041/156819339-b55f22fc-810c-4654-a5eb-8ddf7f5ba9cd.png)

**Comment by VictorTomaili** [comment]
Please use serenity discussions 
https://github.com/serenity-is/Serenity/discussions
