### ISSUE TITLE
Is it possible to make EnvironmentSettings partial class?

### ISSUE THREAD

**Issue by wezmag** [serenity-is/common-features#11]
Hello, 

I have a tiny request.
Is it possible to make [EnvironmentSettings](https://github.com/serenity-is/common-features/blob/master/src/Serenity.Extensions/Serenity.Extensions/Options/EnvironmentSettings.cs) a partial class?
So we can add more properties and re-use the class.

If you team do not have time for this request, I am willing to create a pull request.

Thanks

**Comment by volkanceylan** [comment]
Partial classes can only work inside one assembly. So it will not help you at all. Subclass it and register your own class in Startup like we do for EnvironmentSettings. You can use same section.

**Comment by wezmag** [comment]
Thanks, I almost forgot I can inherit it.
