### ISSUE TITLE
Incorrect idPrefix used for CustomerForm in "Another Form In Tab" example

### ISSUE THREAD

**Issue by DGoertzen** [serenity-is/common-features#21]
Line 27 of https://github.com/serenity-is/common-features/blob/master/src/Serenity.Demo.BasicSamples/Modules/Dialogs/OtherFormInTab/OtherFormInTabDialog.ts is currently:
        this.customerForm = new CustomerForm((this.customerPropertyGrid as any).idPrefix);

For this.customerForm to work correctly to access editors Line 27 should be changed to:
        this.customerForm = new CustomerForm(this.idPrefix + "_Customer_");

As a note, "new PropertyGrid" (in line 20 of the same file) does not seem to do anything with the option "idPrefix: this.idPrefix + "_Customer_","  I don't know if this is intentional, or a bug.   I think if "new PropertyGrid" actually used that idPrefix option, then line 27 would, in fact, be correct.

**Comment by volkanceylan** [comment]
I think it is correct and working as properly, property grid takes a prefix for its editors ids and we are using them to create the form accessor.

**Comment by volkanceylan** [comment]
var editorId = this.options.idPrefix + item.name;

see propertygrid.ts

**Comment by DGoertzen** [comment]
Thanks for the quick response.  

If I use the default code in https://github.com/serenity-is/common-features/blob/master/src/Serenity.Demo.BasicSamples/Modules/Dialogs/OtherFormInTab/OtherFormInTabDialog.ts, when I try to use this.customerForm to access editors, I receive an error of:  "Searching for widget of type '_theeditorname_ on a non-existent element! ()."

For my specific code implementation, as I looked into the error, I observed that the idPrefix of the PropertyGrid did not seem to be getting set correctly after the call to new

After executing the following code:
```
        this.reportsPropertyGrid = new PropertyGrid(this.byId("ReportsPropertyGrid"), {
            idPrefix: this.idPrefix + "_Reports_",
            items: getForm(ReportsForm.formKey).filter(x => x.name != 'ReportId'),
            useCategories: true
        });
```
the debugger showed that this.reportsPropertyGrid.idPrefix = 'Serenity_PropertyGrid22_'.  This seemed odd to me as, based ont the parameters provided to new PropertyGrid, I would have expected it to be Kardiograph_Reports_ObservationReportsExtendedDialog4__Reports.  Here is a screen shot of my debugger show the value of this.idPrefix and this.reportsPropertyGrid
![image](https://user-images.githubusercontent.com/22012694/212998815-59cd8f36-9941-4ecc-850f-3ddd41210be0.png)
Then, if I follow the example in OtherFormInTabDialog.ts, my version of the code is:
```
     this.reportsForm = new ReportsForm((this.reportsPropertyGrid as any).idPrefix);
```
the debugger shows that the this.reportsForm.idPrefix = 'Serenity_PropertyGrid22_'.
![image](https://user-images.githubusercontent.com/22012694/212999658-71bafef1-3ac0-452f-8060-896b5604fd6f.png)

Then, trying to use this.reportsForm to access any editors, I get the error mentioned above of "Searching for widget of type '_theeditorname_ on a non-existent element! (). "

The idPrefix seemed to be the problem to me, so I changed the line of code above to the following:
```
     this.reportsForm = new ReportsForm(this.idPrefix + "_Reports_");
```
When I do that, everything works fine.

Therefore, I think there may be a problem with the call to new PropertyGrid not correctly setting the idPrefix on the PropertyGrid itself.  I hope that is clear.

Thanks.

**Comment by volkanceylan** [comment]
Hmm, ok i see what is going on here. We recently moved idPrefix up from TemplatedWidget to Widget. PropertyGrid had already an idPrefix getter which returns the value from its options. I think the getter is overridden by the idPrefix auto calculated from the base widget class. If you look at debug result, idPrefix is correct in the options. 

I would expect the subclass to win, but seems like thats not the case. Probably one is set in constructor, while other is a getter definition. Might be a bug with TypeScript or esbuild.

Until we fix that, use this.customerGrid.options.idPtefix

**Comment by volkanceylan** [comment]
:) Looking at it again, PropertyGrid never had a "idPrefix" field or getter, The example was wrong, but as the form was not used in the example it did not fail. Probably another reason to avoid "any".

**Comment by volkanceylan** [comment]
There was a "get_idPrefix" method left from Saltaralle times which was access as .idPrefix in C# code, the example was written in those times, and converted to TypeScript in a wrong way

**Comment by DGoertzen** [comment]
Thanks for looking into this and your detailed responses.
