### ISSUE TITLE
CKEditor default script path set incorrectly

### ISSUE THREAD

**Issue by DGoertzen** [serenity-is/common-features#23]
I upgraded my project to 6.5.2.   When I did this, HtmlNoteContentEditor failed to load ckeditor.js correctly.  The problem is caused by the line 201 in [htmlcontenteditor.ts](https://github.com/serenity-is/Serenity/blob/ddbf3ef72e6e094649c07049ec57435e8794dcb1/src/Serenity.Scripts/corelib/src/ui/editors/htmlcontenteditor.ts)

```
    static CKEditorVer = "4.7.1";
    static CKEditorBasePath: string;

    static getCKEditorBasePath(): string {
        var path = HtmlContentEditor.CKEditorBasePath;
        if (path == null) {
            // @ts-ignore
            if (typeof CKEDITOR_BASEPATH !== "undefined" && CKEDITOR_BASEPATH)
                // @ts-ignore
                path = CKEDITOR_BASEPATH;
            else
                return "~/Scripts/ckeditor/";
        }
        if (endsWith(path, '/'))
            return path;
        return path + '/';
    }
```
The correct path that should be returned is "~/Serenity.Assets/Scripts/ckeditor/".  It seems that this was worked around in the Customer demo by adding line 11 to [CustomerIndex.cshtml](https://github.com/serenity-is/common-features/blob/e905fcfc4941d32519443f3d4c9e69a230745cbc/src/Serenity.Demo.Northwind/Areas/Serenity.Demo.Northwind/Customer/CustomerIndex.cshtml).

`<script>var CKEDITOR_BASEPATH = '@ContentHashCache.ResolvePath(Context.Request.PathBase, "~/Serenity.Assets/Scripts/ckeditor/")';</script>`

It appears to me that a better solution is to update htmlcontenteditor.ts as then it will just work without needing to add additional code to the .cshtml files.  However, it could be I am not aware of some reason why line 201 of htmlcontenteditor.ts cannot be changed from 
`return "~/Scripts/ckeditor/";`
to
`return "~/Serenity.Assets/Scripts/ckeditor/";`

Alternatively, the line:
`HtmlContentEditor.CKEditorBasePath = "~/Serenity.Assets/Scripts/ckeditor/";`
can be added to ScriptInit.ts after 
`EntityDialog.defaultLanguageList = siteLanguageList;`
That line was added automatically to my previous project, but was not in that new project I created.

**Comment by volkanceylan** [comment]
It was the default for compatibility reasons, and we were overriding it in ScriptInit.ts, but in recent version we removed that causing a breaking change. I think we should change the default as not much people use so old version now.

**Comment by DGoertzen** [comment]
Thanks for the quick response
