### ISSUE TITLE
Oracle supports auto increment ID from version 12c (Year 2013)

### ISSUE THREAD

**Issue by dfaruque** [serenity-is/common-features#30]
https://github.com/serenity-is/common-features/blob/fc85fa206a056b3c3484330fa1dc6d717ae86b80/src/Serenity.Extensions/Modules/MigrationUtils/MigrationUtils.cs#L74C20-L74C20

Here, we may remove the special method for creating an Oracle identity column.

If someone needs to work with a very older version of Oracle then he should manage that in migration himself.

Since the `MigrationUtils` moved to Serenity.Extension package, default behavior should be based on the majority of the users who use Oracle database in some projects.

**Comment by volkanceylan** [comment]
Customers cannot modify migrations from future packages so it is better to be safe for now.
