### ISSUE TITLE
queryString Sorunu

### ISSUE THREAD

**Issue by fatihozdemir23** [serenity-is/common-features#38]
Aşağıdaki örnekteki gibi yapmaya çalışıyorum fakat **ReferenceError: Proko is not defined** hatası alıyorum
https://github.com/serenity-is/common-features/blob/e4b073651ab9f7cd43f826ca8cc4e6d9875f3dbb/src/Serenity.Demo.Northwind/Areas/Serenity.Demo.Northwind/Order/OrderIndex.cshtml#L22

script kodum bu şekilde
![issue](https://github.com/serenity-is/common-features/assets/17467992/f4232224-bf6e-43e1-aaf7-4d416a98d2c1)

Grid Sınıfı
![grid](https://github.com/serenity-is/common-features/assets/17467992/1b1102ca-c21c-44c9-add1-da1daa4d0b39)

**Comment by VictorTomaili** [comment]
Merhaba Fatih Bey,

Sorularınızı serenity organizasyonunda discussions menüsünden sorabilirsiniz. Lütfen bir hata olduğuna emin olmadan issue açmayınız. Yine de sorunuzu aşağıda cevaplıyorum. 

Örnek olarak [buradaki dashboard](https://github.com/serenity-premium/startsharp/blob/master/src/StartSharp.Web/Modules/Common/Dashboard/DashboardIndex.cshtml) sayfasini inceleyebilirsiniz. 

Aradaki fark order modülü ana projeden bağımsız olduğu için script bundle yapısı farklı ve namespace desteğini koruyor. Fakat sizin javascript kodlarınız Proko namespace yapısıyla oluşturulmuyor. ESM yapısıyla grid ve fonksiyonları import etmeniz gerekiyor. Bu sebeple Proko namespace'ini bulamıyor. ESM entry point denilen bu javascript dosyaları, doğru path ile projeye dahil edilmesi gerekiyor. Bunun için cs ve cshtml tarafında yardımcı fonksiyonlarını kullanabilirsiniz. 

Bir tane `BasvurularPage.ts` dosyası oluşturun. İçerisinde aşağıdaki gibi bir kod olması gerekiyor
```ts
// burada ihtiyaç duyulan (grid ve gridPageInit fonksiyonuna ait) import satırları olacak

export default function pageInit({ durumId }: { durumId: number }) {
    let basvurularGrid = new BasvurularGrid();
    basvurularGrid.DurumId = durumId;
    gridPageInit(basvurularGrid)
}
```

cshtml sayfasında bu şekilde import edebilirsiniz
```cshtml
import pageInit from '@Html.ResolveWithHash(ESM.Modules.Proko.Proko.BasvurularPage)';
pageInit({
//parametreler, model vb.
})
```
